services:
  mongodb:
    image: mongo:6.0
    container_name: mac_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mac_network
    # Adiciona um teste de saúde para avisar quando o Mongo aceitar conexões
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.0-alpine
    container_name: mac_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mac_network
    # Adiciona um teste de saúde para avisar quando o Redis aceitar conexões
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: mac_api
    ports:
      - "8000:8000"
    environment:
      # Passamos explicitamente as URLs usando os nomes dos serviços acima
      - MONGO_URI=mongodb://mongodb:27017/catalogo
      - REDIS_URL=redis://redis:6379
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mac_network

networks:
  mac_network:
    driver: bridge

volumes:
  mongo_data:
  redis_data: